-- 코드를 입력하세요
WITH RECURSIVE CTE AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM CTE
    WHERE HOUR+1<24
)

SELECT CTE.HOUR AS HOUR, COUNT(HOUR(A.DATETIME)) AS COUNT
FROM CTE LEFT JOIN ANIMAL_OUTS A
ON CTE.HOUR=HOUR(A.DATETIME)
GROUP BY HOUR