-- 코드를 입력하세요
WITH CTE AS(
    SELECT *,(
        SELECT COUNT(DISTINCT USER_ID)
        FROM USER_INFO
        WHERE DATE_FORMAT(JOINED,'%Y') LIKE 2021
    ) AS CNT
    FROM USER_INFO 
    WHERE DATE_FORMAT(JOINED,'%Y') LIKE 2021
)

SELECT DATE_FORMAT(SALES_DATE,'%Y') AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,ROUND(COUNT(DISTINCT U.USER_ID)/CNT,1) AS PUCHASED_RATIO
FROM CTE U RIGHT JOIN ONLINE_SALE O ON U.USER_ID=O.USER_ID
WHERE U.USER_ID IS NOT NULL
GROUP BY YEAR,MONTH
ORDER BY YEAR, MONTH