-- 코드를 입력하세요
SELECT HISTORY_ID, 
    ROUND(IF(
        (1+DATEDIFF(END_DATE, START_DATE))<7, 
        ((1+DATEDIFF(END_DATE, START_DATE))*DAILY_FEE),
        ((1+DATEDIFF(END_DATE, START_DATE))*DAILY_FEE)*(1-DISCOUNT_RATE/100)
    )) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID=H.CAR_ID 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE=P.CAR_TYPE AND DURATION_TYPE = (
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN 90
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN 30
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN 7
        ELSE NULL
    END)
WHERE C.CAR_TYPE="트럭"
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC