-- 코드를 입력하세요
SELECT APNT_NO,PT_NAME,	P.PT_NO,	A.MCDP_CD,	DR_NAME,	APNT_YMD
FROM DOCTOR D JOIN APPOINTMENT A ON D.DR_ID=A.MDDR_ID JOIN PATIENT P ON P.PT_NO=A.PT_NO
WHERE APNT_CNCL_YN NOT LIKE 'Y' AND A.MCDP_CD="CS" AND APNT_YMD LIKE "2022-04-13%"
ORDER BY APNT_YMD