SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, SUBSTR(R.CREATED_DATE,1,10) AS CREATED_DATE
FROM USED_GOODS_BOARD as B inner join USED_GOODS_REPLY as R
ON B.BOARD_ID=R.BOARD_ID
WHERE SUBSTR(B.CREATED_DATE,1,7)='2022-10'
ORDER BY R.CREATED_DATE, B.TITLE;