WITH CTE AS (
    SELECT ID, NAME, CATEGORY
    FROM SKILLCODES JOIN DEVELOPERS
    WHERE SKILL_CODE&CODE=CODE
), GA AS (
    SELECT DISTINCT ID
    FROM CTE
    WHERE NAME="Python" AND ID IN (
        SELECT DISTINCT ID
        FROM CTE
        WHERE CATEGORY="Front End"
    )
), GB AS (
    SELECT DISTINCT ID
    FROM CTE
    WHERE NAME="C#"
), GC AS (
    SELECT DISTINCT ID
    FROM CTE
    WHERE CATEGORY="Front End"
)

SELECT CASE
    WHEN ID IN (SELECT ID FROM GA) THEN 'A'
    WHEN ID IN (SELECT ID FROM GB) THEN 'B'
    WHEN ID IN (SELECT ID FROM GC) THEN 'C'
END AS GRADE,
ID, EMAIL
FROM DEVELOPERS
WHERE ID in (SELECT ID FROM GA) OR ID in (SELECT ID FROM GB) OR ID in (SELECT ID FROM GC)
ORDER BY GRADE, ID